# Workings with Recomended Systems

In [18]:
import pandas as pd
import numpy as np

# Datasets Utilised in our Analysis

In [21]:
#Load the u.user file into a dataframe
# u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']

# u_cols2 = ['user_id', 'age', 'sex', 'occupation', 'zip_code']

users = pd.read_csv('./ml-1m/users_u1.csv', sep='|', encoding='latin-1')
users.head()

1  F  1.1  10  48067
0  2  M   56  16  70072
1  3  M   25  15  55117
2  4  M   45   7  02460
3  5  M   25  20  55455
4  6  F   50   9  55117

### Add some titles back !

In [22]:
users = pd.read_csv('./ml-1m/users_u1.csv', sep='|', names=u_cols,
 encoding='latin-1')

users.head()

user_id age  sex  occupation zip_code
0        1   F    1          10    48067
1        2   M   56          16    70072
2        3   M   25          15    55117
3        4   M   45           7    02460
4        5   M   25          20    55455

In [25]:
users[users['zip_code'] == '48067']

user_id age  sex  occupation zip_code
0           1   F    1          10    48067
582       583   F   25           0    48067
1509     1510   F   25           1    48067
2097     2098   M   35          20    48067
4516     4517   F   18           1    48067
4951     4952   F   25          14    48067

In [26]:
#Load the u.data file into a dataframe
r_cols = ['user_id', 'movie_id', 'rating', 'timestamp']

ratings = pd.read_csv('./ml-1m/ratings_r1.csv', sep='|', names=r_cols,
 encoding='latin-1')

ratings.head()

user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [32]:
ratings[(ratings['user_id'] == 196) & (ratings['movie_id'] == 242)]

Empty DataFrame
Columns: [user_id, movie_id, rating, timestamp]
Index: []

In [33]:
#Drop the timestamp column
ratings = ratings.drop('timestamp', axis=1)

In [34]:
#Import the train_test_split function
from sklearn.model_selection import train_test_split

#Assign X as the original ratings dataframe and y as the user_id column of ratings.
X = ratings.copy()
y = ratings['user_id']

#Split into training and test datasets, stratified along user_id
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify=y, random_state=42)

In [45]:
#y_true[0:6]

In [35]:
#Import the mean_squared_error function
from sklearn.metrics import mean_squared_error

#Function that computes the root mean squared error (or RMSE)
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [63]:
baseline(user_id, movie_id)

NameError: name 'user_id' is not defined

In [38]:
#Define the baseline model to always return 3.
def baseline(user_id, movie_id):
    return 3.0

In [79]:
cf_model = baseline

In [110]:
print (len(X_test['user_id']))
print (len(X_test['movie_id']))
# print (user, movie) in id_pairs])
len(X_test['movie_id'])
       
print (len(X_test['user_id'][0:5]))
print (len(X_test['movie_id'][0:5]))

250053
250053
5
5


In [113]:
id_pairs2 = zip(X_test['user_id'][0:14], X_test['movie_id'][0:14])

print(tuple(id_pairs2))
print(id_pairs2)

((2496, 2857), (4865, 1237), (3044, 1090), (4083, 348), (5603, 969), (3967, 1027), (2781, 2952), (3824, 786), (4195, 1941), (96, 2571), (278, 2635), (5235, 3060), (2997, 2374), (5957, 1126))


In [81]:
id_pairs = zip(X_test['user_id'], X_test['movie_id'])

# Gain Undertanding the ZIP function in Python

In [92]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica", "Vicky")

x = zip(a, b)

#use the tuple() function to display a readable version of the result:

print(tuple(x))

(('John', 'Jenny'), ('Charles', 'Christy'), ('Mike', 'Monica'))


In [82]:
y_pred = np.array([cf_model(user, movie) for (user, movie) in id_pairs])

In [83]:
id_pairs = zip(X_test['user_id'], X_test['movie_id'])
#print(id_pairs)

#Predict the rating for every user-movie tuple
y_pred = np.array([cf_model(user, movie) for (user, movie) in id_pairs])

In [88]:
for i in id_pairs:
    print(i)

In [84]:
y_pred

array([3., 3., 3., ..., 3., 3., 3.])

In [114]:
y_true = np.array(X_test['rating'])
y_true

array([3, 5, 4, ..., 4, 1, 3], dtype=int64)

In [115]:
rmse(y_true, y_pred)

1.2579016451581717

In [116]:
score(baseline)

1.2579016451581717

In [117]:
rmse(y_true, y_pred)

1.2579016451581717

In [49]:
#Function to compute the RMSE score obtained on the testing set by a model

def score(cf_model):
    
    #Construct a list of user-movie tuples from the testing dataset
    id_pairs = zip(X_test['user_id'], X_test['movie_id'])
    #print(id_pairs)
    
    #Predict the rating for every user-movie tuple
    
    y_pred = np.array([cf_model(user, movie) for (user, movie) in id_pairs])
    
    #Extract the actual ratings given by the users in the test data
    y_true = np.array(X_test['rating'])
    
    #Return the final RMSE score
    return rmse(y_true, y_pred)

In [74]:
X_test['user_id'][0:5]

414535    2496
810760    4865
495801    3044
681730    4083
926937    5603
Name: user_id, dtype: int64

In [65]:
baseline

<function __main__.baseline(user_id, movie_id)>

In [41]:
baseline

<function __main__.baseline(user_id, movie_id)>

In [46]:
#Build the ratings matrix using pivot_table function
r_matrix = X_train.pivot_table(values='rating', index='user_id', columns='movie_id')

r_matrix.head()

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5          NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN  ...   

movie_id  3943  3944  3945  3946  3947  3948  3949  3950  3951  3952  
user_id                                                               
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 3669 columns]

In [101]:
r_matrix[3].mean()

3.0417827298050137

In [104]:
for (user, movie) in id_pairs:
    print(tuple(id_pairs))

In [ ]:
def score(cf_model):
    
    #Construct a list of user-movie tuples from the testing dataset
    id_pairs = zip(X_test['user_id'], X_test['movie_id'])
    #print(id_pairs)
    
    #Predict the rating for every user-movie tuple
    
    y_pred = np.array([cf_model(user, movie) for (user, movie) in id_pairs])
    
    #Extract the actual ratings given by the users in the test data
    y_true = np.array(X_test['rating'])
    
    #Return the final RMSE score
    return rmse(y_true, y_pred)

In [47]:
#User Based Collaborative Filter using Mean Ratings
def cf_user_mean(user_id, movie_id):
    
    #Check if movie_id exists in r_matrix
    if movie_id in r_matrix:
        #Compute the mean of all the ratings given to the movie
        mean_rating = r_matrix[movie_id].mean()
    
    else:
        #Default to a rating of 3.0 in the absence of any information
        mean_rating = 3.0
    
    return mean_rating

In [120]:
r_matrix[1].mean()

4.126103404791929

In [123]:
for i in range(1,3):
    print(i)
    print(r_matrix[i].mean())

1
4.126103404791929
2
3.2111111111111112


In [48]:
#Compute RMSE for the Mean model
score(cf_user_mean)

0.9807064418668026

In [72]:
r_matrix

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                               ...   
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5          NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
6036       NaN   NaN   NaN   2.0   NaN   3.0   NaN   NaN   NaN   NaN  ...   
6037       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
6038       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
6039       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
6040       3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   

movie_id  3943  3944  3945  3946  3947  3948  3949  3950  3951  3952  
user_id                                                               
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
6036       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
6037       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
6038       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
6039       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
6040       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[6040 rows x 3669 columns]

# Insights On Cosine Similarity

![title](image/cosine_sim.png)

**Figure 1**: The cosine of the angle between two vectors is a measure of how similar they are. From (2) below.

In [127]:
from sklearn.metrics.pairwise import cosine_similarity

In [124]:
array_vec_1 = np.array([[12,41,60,11,21]])
array_vec_2 = np.array([[40,11,4,11,14]]) 

In [125]:
array_vec_1

array([[12, 41, 60, 11, 21]])

In [140]:
# if the vectors are say identical, as EXPECTED their cosine similarity fucntion returns a 1.

# Python code to demonstrate the working of cos()
# importing "math" for mathematical operations 

import math
print ("Cosine of ZERO:",  math.cos(0))

print ("Cosine Similarity between two identical vectors, i.e. having an angle of zero between them:", cosine_similarity(array_vec_1, array_vec_1))


Cosine of ZERO: 1.0
Cosine Similarity between two identical vectors, i.e. having an angle of zero between them: [[1.]]


### My References to replicate or produce the above work

1- From <a href="https://www.geeksforgeeks.org/python-math-cos-function/">Geeks for Geeks</a>, explaining the cosine function.

2- From <a href="https://datascience-enthusiast.com/DL/Operations_on_word_vectors.html">Fisseha Berhane and datascience-enthusiast.com</a>, explaining the **cosine similarity**, a crucial implemetntion point in Recommnestion Systems. Vizuals always are great help, hence their inclusion above.


